//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.14 at 04:06:48 PM CET 
//


package com.soursesense.emanuelepicariello.newscombinatorsoap.news;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NewsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NewsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="hackerNews"/>
 *     &lt;enumeration value="nyTimesNews"/>
 *     &lt;enumeration value="all"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NewsType")
@XmlEnum
public enum NewsType {

    @XmlEnumValue("hackerNews")
    HACKER_NEWS("hackerNews"),
    @XmlEnumValue("nyTimesNews")
    NY_TIMES_NEWS("nyTimesNews"),
    @XmlEnumValue("all")
    ALL("all");
    private final String value;

    NewsType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NewsType fromValue(String v) {
        for (NewsType c: NewsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
