//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 04:07:03 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.newscombinator.com/sample", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.soursesense.emanuelepicariello.newscombinatorsoap.news;
